FROM postgres:${PG_VERSION}-alpine

# Install dependencies
RUN apk add --no-cache clang-analyzer make musl-dev gcc python3 py-virtualenv curl;

# Environment
ENV LANG=C.UTF-8 PGDATA=/pg/data

# Make directories
RUN	mkdir -p ${PGDATA} && \
	mkdir -p /pg/sr_plan

# Grant privileges
RUN	chown postgres:postgres ${PGDATA} && \
	chown postgres:postgres /pg/sr_plan && \
	chmod a+rwx /usr/local/lib/postgresql && \
	chmod a+rwx /usr/local/share/postgresql/extension

COPY run_tests.sh /run.sh
RUN chmod 755 /run.sh

ADD . /pg/sr_plan
WORKDIR /pg/sr_plan

USER postgres
ENTRYPOINT /run.sh
